Update config.md
convos-chat/www.convos.chat pull request #8
Opened 2022-03-09 20:07 UTC by PeGaSuS-Coder

Fixed:
- CONVOS_WEBIRC_PASSWORD_LOCALHOST not being displayed properly due to markdown malformation

Added:
- User systemd unit file
- Instructions how to enable user systemd without root rights and respective user commands

2022-03-13 02:00 UTC, jhthorsen requested changes
Thanks a lot for the PR! A lot of great information here, but I do think some things needs adjustments.

For the future: It's much easier to accept a PR if it only has one change. (This PR contains bug fixes and new information)

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +2. Set the following environment variable to enable WEBIRC:
Please remove the extra space.

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +Here is an example of a user systemd file, that can be placed in `.config/systemd/user/convos.service`.
Please add $HOME to the path. Same below.

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +    loginctl enable-linger
Does this have to be run as root? Either way, please add an extra line break.

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +    systemctl --user enable systemd-tmpfiles-clean.timer && systemctl --user disable systemd-tmpfiles-clean.timer
What is systemd-tmpfiles-clean? Either way, I think it's easier if you just tell the user how to create the directory manually.

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +    Environment=CONVOS_REVERSE_PROXY=1
Please remove CONVOS_REVERSE_PROXY. It can potentially be harmful to have this in the default config, when not running behind a reverse proxy.

2022-03-13 02:00 UTC, jhthorsen commented on doc/config.md
> +    Environment=CONVOS_HOME=/home/$USER/convos
Why not use the default? I think that using the default will make it easier when reading other instructions such as https://convos.chat/doc/faq#where-does-convos-store-logs-settings-and-uploaded-files

If using the default, then maybe the CONVOS_LOG_FILE need to be adjusted as well, and maybe you need a PreExecStart command to create that directory. (Not sure about that though)

2022-03-13 09:31 UTC, jhthorsen requested changes

2022-03-13 09:31 UTC, jhthorsen commented on doc/config.md
> +Then you need to create the `$HOME/.config/systemd/user` folder mannually or using the following command:
"mannually"

2022-03-13 09:44 UTC, jhthorsen commented on doc/config.md
> +        systemctl --user enable systemd-tmpfiles-clean.timer && systemctl --user disable systemd-tmpfiles-clean.timer
Why is the indentation different here from the code below?

2022-03-13 23:28 UTC, jhthorsen commented on doc/config.md
> +    systemctl --user enable systemd-tmpfiles-clean.timer && systemctl --user disable systemd-tmpfiles-clean.timer
I'm still curious about what systemd-tmpfiles-clean is, and I still think it's more confusing than helpful.

2022-03-13 23:28 UTC, jhthorsen commented on doc/config.md
> +    loginctl enable-linger
"Does this have to be run as root?" has not been answered.

2024-08-15 14:09 UTC, TehPeGaSuS commented
I need to redo some things. This is a complete mess!!!
I'll open a new PR

2024-08-15 14:09 UTC, closed without merging